### ISSUE TITLE
mention date-fns in the README

### ISSUE THREAD

**Issue by callmecavs** [jmblog/how-to-optimize-momentjs-with-webpack#1]
[`date-fns`](https://date-fns.org/) is a library that provides similar functionality to `moment`, but more modularity via its exports pattern.  It follows the "one function per file" methodology, and ships from npm with tree-shaking-ready distribution files (perfect for webpack2/rollup).

It doesn't require any webpack trickery in regards to configuration to keep what it adds to your bundle size relative to what you actually use.

Might be worth mentioning in the README, at your discretion.  If not, feel free to close this issue - just thought it might be nice to suggest an alternative that comes at a lower cost to configuration.

**Comment by jmblog** [comment]
@callmecavs I have not tried `date-fns` in my projects yet, but I know it has [more pros](https://github.com/date-fns/date-fns/issues/275#issuecomment-264934189) than `moment.js`.

It must be good to mention `date-fns` in the README as you said. I'll add soon.

Thanks for your nice suggestion 👍

**Comment by jmblog** [comment]
https://github.com/jmblog/how-to-optimize-momentjs-with-webpack/commit/3b726fe48a7968ffc63ac34e674170598391a0b9

**Comment by callmecavs** [comment]
@jmblog thanks man, happy to help
