### ISSUE TITLE
"More cons..." is this a typo?

### ISSUE THREAD

**Issue by citypaul** [jmblog/how-to-optimize-momentjs-with-webpack#3]
> date-fns is an alternative libraly to moment.js. It doesn't need this kind of tricky solution and has more cons. It's worth considering.

Where you wrote "more cons" there, did you mean "more benefits"? Just asking as the link provided seems to be selling the benefits, and I found it a little confusing! :)

**Comment by jmblog** [comment]
@citypaul Oh, I made a terrible mistake... I mean "more pros" as you said. Thank you so much for your pointing out.

**Comment by citypaul** [comment]
Ha, no worries! Glad to help. Nice resource by the way :) 🥇
