### ISSUE TITLE
eslint error

### ISSUE THREAD

**Issue by ilaipi** [jmblog/how-to-optimize-momentjs-with-webpack#5]
![image](https://user-images.githubusercontent.com/1689135/40222224-6a915efa-5ab1-11e8-9c25-0910f5eda592.png)

my eslint report a error, does it matter?

to fix it, add a `\`:
```
new webpack.ContextReplacementPlugin(/moment[\\/\\]locale$/, /zh-cn/),
                                             ^
```

it seems work well, but i am not sure.

is `/zh-cn/` works well?

**Comment by jmblog** [comment]
@ilaipi Hi,

The eslint is right. The first escape character is not nessesary. (Both `[\/]` and `[/]` match a `/` character.)

To fix your lint error, just remove it.

```js
new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /zh-cn/),
```

I hope this would help you.

**Comment by ilaipi** [comment]
@jmblog thanks! this means I only load `moment.js` with `zh-cn` local, right?

**Comment by jmblog** [comment]
@ilaipi Yes. To confirm it, please check your bundled file size and search the word `defineLocale` in the file. 👍

**Comment by ilaipi** [comment]
@jmblog Hi,

`moment.js`
![image](https://user-images.githubusercontent.com/1689135/40300029-ae444f70-5d1a-11e8-9c57-db57cbf70970.png)

`_moment`
![image](https://user-images.githubusercontent.com/1689135/40300077-c64ab258-5d1a-11e8-85b7-ae899f42f3a9.png)

these are my bundled analysis, i think the size is right.
I don't know why bundled twice, once is moment, and another is _moment.

## but I can't find `defineLocale` in my bundled file.

**Comment by jmblog** [comment]
@ilaipi I think that this is not caused by ContextReplacementPlugin. I'm sorry that I can not be a help...

**Comment by ilaipi** [comment]
I tried the ignore plugin, and add

```javascript
import 'moment';
import 'moment/locale/zh-cn';
```

to my code. and then i can find `defineLocale` in bundled file.
