### ISSUE TITLE
Dayjs is another good option

### ISSUE THREAD

**Issue by ghost** [jmblog/how-to-optimize-momentjs-with-webpack#7]
dayjs has a smaller core and has very similar APIs so it makes it very easy to migrate.

How about adding dayjs to our readme as well?

Reference : https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by jmblog** [comment]
Thanks for your suggestion.

I think that it's suitable to add the link https://github.com/you-dont-need/You-Dont-Need-Momentjs.
